alias: Auto Off Room
description: ""
triggers:

# ID's have been removed, This is the precense binary sensor
  - type: not_occupied
    device_id: 
    entity_id: 
    domain: binary_sensor
    trigger: device
    for:
      hours: 0
      minutes: 2
      seconds: 0
conditions:
# my conditions are if any of the devices in the room are on
  - condition: or
    conditions:
      - condition: device
        type: is_on
        device_id: 
        entity_id: 
        domain: switch
      - condition: device
        type: is_on
        device_id: 
        entity_id: 
        domain: switch
      - condition: device
        type: is_on
        device_id: 
        entity_id: 
        domain: switch
actions:
#actions are to turn those devices off
  - type: turn_off
    device_id: 
    entity_id: 
    domain: switch
  - type: turn_off
    device_id: 
    entity_id: 
    domain: switch
  - type: turn_off
    device_id: 
    entity_id: 
    domain: switch
  - type: turn_off
    device_id: 
    entity_id: 
    domain: switch
mode: single
